### ISSUE TITLE
Unclear how client is connecting?

### ISSUE THREAD

**Issue by Naatan** [johanbrandhorst/grpcweb-wasm-example#3]
Hi there.. I've been trying to use your example code with the latest version of GRPC and GRPC-web. I've got everything set up the same as you and am stuck trying to understand how this works:

https://github.com/johanbrandhorst/grpcweb-wasm-example/blob/master/frontend/frontend.go#L46

You provide no address in your example. When I do this I run into the following error:

```
initializing client failed: could not connect to gRPC server: failed to build resolver: passthrough: received empty target in Build()
```

Makes sense. How is it meant to connect without knowing the address? Bit confused about how this could work in your example at all.

So I try to address the issue by supplying the actual server address (ie. `localhost:1000`). The obvious problem here is that the client is using standard grpc.. which uses sockets. And sure enough; it gives me an error indicating as much:

```
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp: lookup localhost: Protocol not available"
```

I'm at a bit of a loss trying to understand how your example is meant to work unfortunately.

I realize this is a 4-year-old repo, but sadly I can't find any other resources that are covering what I am trying to do (ie. connect from go-wasm via grpc). In fact, the grpc-web repo seems to be entirely focused on facilitating grpc connections via the web from the server. I see no mention of doing it from the client side in Go (only typescript).

Hopefully, you can provide some insight. Thank you!

**Comment by johanbrandhorst** [comment]
Hi Nathan, I'm so glad you've stumbled across this little tech demo of mine. I apologize for the confusion. My presentation at [dotGo 2019](https://www.youtube.com/watch?v=osVHH7rjpxs) talks a bit more about how this works but the basic thing you're missing is that you need to use a specific branch of grpc-go that I created in 2019. You can see it defined here:

https://github.com/johanbrandhorst/grpcweb-wasm-example/blob/7ffce7e6aa30b47cf59bd277f2d849093e330a63/Gopkg.toml#L18-L21

The branch is still available here: https://github.com/johanbrandhorst/grpc-go/tree/add-grpc-web-client. You should be able to get this all building by ensuring that your `go.mod` points to this branch. The reason `Dial("")` works in this case is because it will use the address of the website that it is hosted on. This works in JS, so it works in Go wasm. It will also avoid any CORS or HTTPS issues, which is nice :).

With all that said, this demo never made its way into the mainstream grpc-go distribution, mainly because there (AFAIK) still is no "transport" interface in which you could switch in a grpc-web transport, and as such, shouldn't be used for anything serious. But it's a cool tech demo!

**Comment by johanbrandhorst** [comment]
I just pushed up a commit that migrates to modules, that should allow you to run the `make serve` and have it all work :). I should migrate the protobuf generation and stuff too but it'll take a bit longer. Feel free to reach out on Gophers Slack if you want to chat more about this.

**Comment by Naatan** [comment]
Thanks for the swift response @johanbrandhorst! I indeed missed that detail. I'll have a play with your fork to see if I can get it working with the latest grpc version. Much appreciated! 🙏

**Comment by johanbrandhorst** [comment]
I went and updated the protobuf generation and asset embedding too, feel free to have a look it should be significantly easier to use. Good luck adapting the code to the modern codebase, it was a hack back then and it'll be the same today I expect 😁.

**Comment by Naatan** [comment]
Above and beyond, much appreciated @johanbrandhorst, thank you!
